# -*- coding: utf-8 -*-
"""
Created on Tue Aug  4 12:30:13 2020

@author: Steve
"""

VALUE_SEPARATOR = "="

EMITTER = "$EMITTER"
EMITTER_ELNOT = "$ELNOT"

EMITTER_MODE = "$EMITTER_MODE"
MODE_NAME = "$MODE_NAME"

GENERATOR = "$GENERATOR"
GENERATOR_NUMBER = "$GENERATOR_NUMBER"

PRI_SEQUENCE = "$PRI_SEQUENCE"

FREQ_SEQUENCE = "$FREQ_SEQUENCE"

END_OF_ENTITY = "$END"

BASE_ARRAY = "BASE"

COMPARISON_ARRAY = "COMPARISON"
