# -*- coding: utf-8 -*-
"""
Created on Tue Aug  4 12:30:13 2020

@author: Steve
"""

VALUE_SEPARATOR = "="

EMITTER = "$EMITTER"
EMITTER_ELNOT = "$ELINT"

EMITTER_MODE = "$EMITTER_MODE"
MODE_NAME = "$MODE_NAME"

GENERATOR = "$GENERATOR"
GENERATOR_NUMBER = "$GENERATOR_NUMBER"

PRI_SEQUENCE = "$PRI_SEQUENCE"

FREQ_SEQUENCE = "$FREQ_SEQUENCE"

PRI_SEGMENT = "$PRI_SEGMENT"

FREQ_SEGMENT = "$FREQ_SEGMENT"

NUMBER_OF_SEGMENTS = "$NUMBER_OF_SEGMENTS"
PRI_SEGMENT_NUMBER = "$PRI_SEGMENT_NUMBER"
FREQ_SEGMENT_NUMBER = "$FREQ_SEGMENT_NUMBER"

END_OF_ENTITY = "$END"



BASE_ARRAY = "BASE"
COMPARISON_ARRAY = "COMPARISON"

BASE_XL_COL_ELNOT_LBL = 1
BASE_XL_COL_ELNOT_VAL = 2
BASE_XL_COL_EMITTER_ATTRIB_LBL = 2
BASE_XL_COL_EMITTER_ATTRIB_VAL = 3
BASE_XL_COL_MODE_LBL = 3
BASE_XL_COL_MODE_VAL = 4
BASE_XL_COL_MODE_ATTRIB_LBL = 4
BASE_XL_COL_MODE_ATTRIB_VAL = 5
BASE_XL_COL_GENERATOR_LBL = 5
BASE_XL_COL_GENERATOR_VAL = 6
BASE_XL_COL_GENERATOR_ATTRIB_LBL = 6
BASE_XL_COL_GENERATOR_ATTRIB_VAL = 7
BASE_XL_COL_PF_SEQUENCE_LBL = 7
BASE_XL_COL_PF_SEQUENCE_VAL = 8
BASE_XL_COL_PF_SEQUENCE_ATTRIB_LBL = 8
BASE_XL_COL_PF_SEQUENCE_ATTRIB_VAL = 9
BASE_XL_COL_PF_SEGMENT_LBL = 9
BASE_XL_COL_PF_SEGMENT_VAL = 10
BASE_XL_COL_PF_SEGMENT_ATTRIB_LBL = 10
BASE_XL_COL_PF_SEGMENT_ATTRIB_VAL = 11


COMP_XL_COL_ELNOT_LBL = 13
COMP_XL_COL_ELNOT_VAL = 14
COMP_XL_COL_EMITTER_ATTRIB_LBL = 14
COMP_XL_COL_EMITTER_ATTRIB_VAL = 15
COMP_XL_COL_MODE_LBL = 15
COMP_XL_COL_MODE_VAL = 16
COMP_XL_COL_MODE_ATTRIB_LBL = 16
COMP_XL_COL_MODE_ATTRIB_VAL = 17
COMP_XL_COL_GENERATOR_LBL = 17
COMP_XL_COL_GENERATOR_VAL = 18
COMP_XL_COL_GENERATOR_ATTRIB_LBL = 18
COMP_XL_COL_GENERATOR_ATTRIB_VAL = 19
COMP_XL_COL_PF_SEQUENCE_LBL = 19
COMP_XL_COL_PF_SEQUENCE_VAL = 20
COMP_XL_COL_PF_SEQUENCE_ATTRIB_LBL = 20
COMP_XL_COL_PF_SEQUENCE_ATTRIB_VAL = 21
COMP_XL_COL_PF_SEGMENT_LBL = 21
COMP_XL_COL_PF_SEGMENT_VAL = 22
COMP_XL_COL_PF_SEGMENT_ATTRIB_LBL = 21
COMP_XL_COL_PF_SEGMENT_ATTRIB_VAL = 22

XL_MISSING_TEXT = "MISSING"
XL_MISSING_TEXT_COLOR = "250, 0, 0"



